### ISSUE TITLE
Invisible Vehicles

### ISSUE THREAD

**Issue by FreedomsFlame** [CattoSalad/VTMB-RTX-Remix#1]
Vehicles are rendered invisible when using base Unofficial Patch with dx70, this occurs even with Remix disabled.
![invisiblecar](https://github.com/CattoSalad/VTMB-RTX-Remix/assets/14211365/f79daa83-d384-4f3b-a6ac-315d2080909b)
Plus Patch does not have this issue
![visiblecar](https://github.com/CattoSalad/VTMB-RTX-Remix/assets/14211365/d9362683-2532-4d3a-a08a-1f7d3b556919)

Removing (vehicle).dx7_2bone.vtx from ../Unofficial_Patch/models/scenery/vehicles/(vehicle) restores the model to default and works as a temporary fix. Can also just delete the entire vehicles folder.

**Comment by CattoSalad** [comment]
![image](https://github.com/CattoSalad/VTMB-RTX-Remix/assets/71943884/b28fd9fb-24eb-445a-86ab-76afefef9a89) ([Source](https://steamcommunity.com/app/2600/discussions/0/4137187221843474738/#c4137187221847123782))

Will be addressed on the next release 👍

**Comment by CattoSalad** [comment]
[Instructions can be found here](https://github.com/CattoSalad/VTMB-RTX-Remix/tree/main/resources/invisible_cars_fix)
